### ISSUE TITLE
Compatibility with Python 3.12: AssertionError: RuntimeError not raised by bdecode

### ISSUE THREAD

**Issue by hrnciar** [breezy-team/fastbencode#23]
Hello, 

I'd like to ask for help. In Fedora, we are using the upcoming Python 3.12 as the main Python in Fedora Rawhide. We are seeing the following test failure:

~~~~
======================================================================
FAIL: test_list_deepnested (fastbencode.tests.test_bencode.TestBencodeDecode.test_list_deepnested)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/fastbencode-0.0.9/fastbencode/tests/test_bencode.py", line 297, in test_list_deepnested
    self._run_check_error(RuntimeError, (b"l" * 100) + (b"e" * 100))
  File "/builddir/build/BUILD/fastbencode-0.0.9/fastbencode/tests/test_bencode.py", line 238, in _run_check_error
    self.assertRaises(exc, self.module.bdecode, bad)
AssertionError: RuntimeError not raised by bdecode
~~~~

**Comment by mgorny** [comment]
I'm seeing the problem again with Python 3.12.3. I'm pretty sure that the commit used to fix it before, so probably something changed in CPython:

```pytb
$ python -m unittest
...............F...................................F.........F............
======================================================================
FAIL: test_dict_deepnested (fastbencode.tests.test_bencode.TestBencodeDecode.test_dict_deepnested)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/fastbencode/fastbencode/tests/test_bencode.py", line 317, in test_dict_deepnested
    self._run_check_error(
  File "/tmp/fastbencode/fastbencode/tests/test_bencode.py", line 234, in _run_check_error
    self.assertRaises(exc, self.module.bdecode, bad)
AssertionError: RuntimeError not raised by bdecode

======================================================================
FAIL: test_dict_deep_nested (fastbencode.tests.test_bencode.TestBencodeEncode.test_dict_deep_nested)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/fastbencode/fastbencode/tests/test_bencode.py", line 447, in test_dict_deep_nested
    self.assertRaises(RuntimeError, self.module.bencode, top)
AssertionError: RuntimeError not raised by bencode

======================================================================
FAIL: test_list_deep_nested (fastbencode.tests.test_bencode.TestBencodeEncode.test_list_deep_nested)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/fastbencode/fastbencode/tests/test_bencode.py", line 433, in test_list_deep_nested
    self.assertRaises(RuntimeError, self.module.bencode, top)
AssertionError: RuntimeError not raised by bencode

----------------------------------------------------------------------
Ran 74 tests in 0.007s

FAILED (failures=3)
```

**Comment by arkamar** [comment]
It seems that Github actions are not catching this issue because extension is not tested:
```
/home/runner/work/fastbencode/fastbencode/fastbencode/__init__.py:51: UserWarning: failed to load compiled extension: No module named 'fastbencode._bencode_pyx'
```
see https://github.com/breezy-team/fastbencode/actions/runs/9449497424/job/26025895754#step:6:13
